### ISSUE TITLE
Error in DCGAN-tensorflow

### ISSUE THREAD

**Issue by Niculuse** [layumi/Person-reID_GAN#8]
information is as follows:
PS F:\tf\GAN_for_ReID\DCGAN-tensorflow-master> python main.py --data_set duke_train --train --input_height 128 --output_
height 128 --options 1
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'crop': False,
 'dataset': 'celebA',
 'epoch': 25,
 'input_fname_pattern': '*.jpg',
 'input_height': 128,
 'input_width': None,
 'learning_rate': 0.0002,
 'options': 1,
 'output_height': 128,
 'output_path': 'duke_result',
 'output_width': None,
 'sample_dir': 'samples',
 'sample_size': 1000,
 'train': True,
 'train_size': inf,
 'visualize': False}
2017-12-02 10:27:00.324224: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2017-12-02 10:27:01.058755: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 860M major: 5 minor: 0 memoryClockRate(GHz): 1.0195
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.65GiB
2017-12-02 10:27:01.065748: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    tf.app.run()
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 78, in main
    sample_dir=FLAGS.sample_dir)
  File "F:\tf\GAN_for_ReID\DCGAN-tensorflow-master\model.py", line 78, in __init__
    imreadImg = imread(self.data[0]);
IndexError: list index out of range
please tell me how to solve it.Thanks for your time!

**Comment by TaihuLight** [comment]
You shoul use the version forked by layumi, it is correct. but my test result on Market1501 is mAP=0.532, rank-1 = 0.7497

**Comment by layumi** [comment]
Hi @Niculuse ，
Sorry for the late response. I didn't notice this issue.
You may refer to https://github.com/layumi/DCGAN-tensorflow
Any question is welcomed.

Thanks for reporting your result @TaihuLight 
Did you test K+1 or baseline result? Are these result right?

**Comment by githublgc** [comment]
> Hi @Niculuse ， Sorry for the late response. I didn't notice this issue. You may refer to https://github.com/layumi/DCGAN-tensorflow Any question is welcomed.
> 
> Thanks for reporting your result @TaihuLight Did you test K+1 or baseline result? Are these result right?

i face the same question.....

i'm sorry to bother you,but i want to know where should i put the data folder if i use windows-system for using GPU ?

i try to put it in DCGAN-tensorflow,but it notwork....

but it seed that just cannot read pictures,so it must use the same version such as tf0.12?
